### ISSUE TITLE
ubi8 over ubi8-minimal for SSSD

### ISSUE THREAD

**Issue by shiube2007** [keycloak/keycloak-containers#362]
### Description

The container from jboss serves 95% of our needs. The other 5% is we want to implement SSSD but the only way to do that is to install through yum (or dnf I suppose) some packages which also require that systemd be running as well.

Looking through the documentation you mention it is built upon ubi8-minimal but ubi8 would provide what we need. Is there a way to either on our end somehow build keycloak on top of that or to provide a tag for building with ubi8 over ubi8-minimal?

### Discussion

https://github.com/keycloak/keycloak/discussions/9379

### Motivation

It allows us to take full advantage of all of keycloak's features.

### Details

I don't fully understand this well but it looks like the only change needed is in the Dockerfile from ubi8-minimal to ubi8

**Comment by stianst** [comment]
Changing from ubi8-minimal to ubi8 increases the container size, and brings it a lot more packages, which in turn results in additional CVEs, so that's not a change we will make.

Adding SSSD would require extending the image regardless, so would be possible to just install additional dependency then, so I don't see a need to do an additional distribution.

I'm going to close this request as we simply don't have enough demand for it, and it can be achieved by simply extending the image, that is if SSSD even runs in a container, which I'm not certain it even does.
